version: '3'

services:
  pgDB-dev:
    image: postgres:16.2-alpine3.19
    container_name: pgDB
    networks:
      - oces-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: oces
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis-dev:
    image: redis/redis-stack:7.2.0-v8
    container_name: redis
    networks:
      - oces-dev
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data-dev:/data
    environment:
      REDIS_ARGS: "--appendonly yes --appendfsync everysec"
    restart: unless-stopped

  worker-dev:
    build:
      context: ./
      dockerfile: worker-dockerfile
    networks:
      - oces-dev
    volumes:
      - ./logs:/app/logs
    ports:
      - "8002:8002"
    privileged: true
    restart: unless-stopped
networks:
  oces-dev:

volumes:
  pg-data-dev:
  redis-data-dev:
