version: '3'

services:
  pgDB:
    image: postgres:16.2-alpine3.19
    container_name: pgDB
    networks:
      - oces
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: oces
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis/redis-stack:7.2.0-v8
    container_name: redis
    networks:
      - oces
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: "--appendonly yes --appendfsync everysec"
    restart: unless-stopped

  server:
    build:
      context: ./
      dockerfile: server-dockerfile
    container_name: server
    networks:
      - oces
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  worker:
    build:
      context: ./
      dockerfile: worker-dockerfile
    networks:
      - oces
    volumes:
      - ./logs:/app/logs
    privileged: true
    restart: unless-stopped

networks:
  oces:

volumes:
  pg-data:
  redis-data:
